### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [st8st8/django-oscar-stripe-sca#2]
Do you intend to release this soon onto PyPI, perhaps marked as a pre-release if not comfortable doing a full release?

**Comment by st8st8** [comment]
Yes - I'm happy to, if its helpful.  I'll need to review the setup files and create myself pypi accounts etc. I'll get something up this week.

**Comment by st8st8** [comment]
This has been added to PyPI:

https://pypi.org/project/django-oscar-stripe-sca/

Thanks for getting involved...
