### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by deadxd** [st8st8/django-oscar-stripe-sca#5]
can add to README how to use ?
I tried to use
1. pip install django-oscar-stripe-sca
2. inside INSTALLED_APPS = [
     'oscar_stripe_sca',
]
3. I put the variables in settings.py:
STRIPE_SECRET_KEY ='sk_test_51'
STRIPE_PUBLISHABLE_KEY ='pk_test_51'
STRIPE_CURRENCY ='USD'
but it didn't work, what would be missing?

best regards

**Comment by st8st8** [comment]
I've added a quick documentation for the settings - my guess is that you will need to add URLs for payment success and payment cancel.  Extend the three views in your checkout app, create URLS for them and set the STRIPE_PAYMENT_SUCCESS_URL and STRIPE_PAYMENT_CANCEL_URL accordingly.  Let me know if that helps.

**Comment by deadxd** [comment]
in this case django-oscar already implements the success URL which is: 
checkout:thank-you 
or 
checkout/thank_you.html 
we would only have to implement the cancel URL with some errors

**Comment by deadxd** [comment]
Wouldn't it be more correct if the 'preview' came before the 'payment' or 'pay time'?
from what i saw we pay first then we go to the preview area and then to the 'thank_you' or 'cancel' area after being implemented

**Comment by st8st8** [comment]
I've had another look through the code, reminded myself more how it works, and updated the readme again.

Payment uses Charge & Capture, so you must use the three URLs provided by the app.   If the user wants to use Stripe as a payment method, then you should use the PaymentDetailsView provided here.

The PaymentDetailsView sets up Stripe, redirects and does the Charge step.  The Success view handles the response from Stripe and sets up the form, which when submitted does the Capture step.

**Comment by arnavmah** [comment]
Hi @st8st8 and everyone else on this thread, thanks for creating and maintaining this package. 
I have followed the same steps that @deadxd mentioned: 
pip install django-oscar-stripe-sca
inside INSTALLED_APPS = [
'oscar_stripe_sca',
]
I put the variables in settings.py:
STRIPE_SECRET_KEY ='sk_test_51'
STRIPE_PUBLISHABLE_KEY ='pk_test_51'
STRIPE_CURRENCY ='USD'

On top of that, have also added the following URLs: 

STRIPE_PAYMENT_SUCCESS_URL = "http://localhost:8000/preview-stripe/<int:basket_id>/"  
STRIPE_PAYMENT_CANCEL_URL = "http://localhost:8000/payment-cancel/<int:basket_id>/"  

However, I am seeing the default payment_details page on checkout (which mentions all the possible integrations). Please let me know if I am missing something. Do I still have to fork the checkout app and its templates?

**Comment by st8st8** [comment]
@arnavmah - it sounds like you need to make sure django_oscar_stripe_sca's PaymentDetailsView get used.  You may have the fork the checkout app to do this (https://django-oscar.readthedocs.io/en/stable/topics/fork_app.html) and then update the apps.py to point the payment_details_view to the new URL, something like this:

`
from oscar_stripe_sca import views as stripe_sca_views


class MyShopCheckoutConfig(CheckoutConfig):
    name = 'apps.checkout'

    def ready(self):
        super().ready()
        self.payment_details_view = stripe_sca_views.StripeSCAPaymentDetailsView
`

If there's a way to avoid forking the checkout app, I can't think of it just now....

**Comment by arnavmah** [comment]
Appreciate the prompt response @st8st8. However, still unable to implement this. 

1) Couldn't find CheckoutConfig class in the source code apps/checkout/views.py so I followed these steps: 
from oscar.apps.checkout.views import PaymentDetailsView as BasePaymentDetailsView

from oscar_stripe_sca import views as stripe_sca_views

class NewPaymentDetailsView(BasePaymentDetailsView):
    name = 'apps.checkout'

    def ready(self):
        super().ready()
        self.payment_details_view = stripe_sca_views.StripeSCAPaymentDetailsView

2) Created a new template folder oscar_stripe_sca and extended the package's stripe_payment_details.html in this way:
{% extends 'django-oscar-stripe-sca/templates/oscar_stripe_sca/stripe_payment_details.html' %}
This didn't work.

Also tried adding the code to the templates/oscar/checkout/payment_details.html:
{% extends 'django-oscar-stripe-sca/checkout/stripe_payment_details.html' %}
{% load i18n static %}
{% load currency_filters %}

{% block payment_details_content %}
    {{ block.super }}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://js.stripe.com/v3"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            setTimeout(function() {
                console.log("Redirecting to stripe");
                var stripe = Stripe('{{ stripe_publishable_key }}');
                stripe.redirectToCheckout({
                    sessionId: '{{ stripe_session_id }}'
                });
            }, 1000);
        });
    </script>
{% endblock %}

I got a 500 error with this method too. Is there anything else I should be doing? Also, apologies for a lengthy response.

**Comment by st8st8** [comment]
1.
    from oscar.apps.checkout.apps import CheckoutConfig

2.
    It looks like the template references in the views.py in this code is wrong.  I've made an update to this which should wire up the views to the provided templates - take a look at my last commit.  I've added you as a collaborator to this repo, hopefully that will allow you to make changes if you need. The feedback is helpful, thanks.

**Comment by j2l** [comment]
I'm also puzzled to get it working, is there a minimal working sandbox visible somewhere?

**Comment by st8st8** [comment]
Let me see what I can put together....

**Comment by st8st8** [comment]
OK I've updated the sandbox in master here.  I suspect the problem you were having is that you need to import the views in the ready function, not at the top of the file (which is unusual).  Take a look, let me know.

**Comment by j2l** [comment]
Thank you @st8st8 !

settings.py `from settings_local import *` doesn't work for me:
`ModuleNotFoundError: No module named 'settings_local'`
not sure what versions you use, mine are Django==4.2.9, django-oscar==3.2.2

After commenting this line and migrating, it runs and I can go up to checkout, then:
```
<h1>AttributeError
       at /checkout/payment-details/</h1>
  <pre class="exception_value">'NoneType' object has no attribute 'email'</pre>
  
Request Method: | GET
-- | --
http://127.0.0.1:8000/checkout/payment-details/
```

I can't work more on it today but if you update it, I'll have a look tomorrow.

**Comment by st8st8** [comment]
settings_local.py - that's a fair point.  I've added a note in the readme and settings.py file about why that is there.

Versions - yes, that's the same as what I have. I tried to be a bit more generous in the requirements because upgrading Oscar needs to be done with care.  I'm guessing slightly here, but I think that's the versions of Django and Oscar that I was using when I built this originally.

Exception - my guess there is that you're not logged in.  In fairness, I've not tested this against anonymous checkouts, so I'll need to do that.  I'll try to do that today.  In the meantime, let me know if the checkout works if you're logged in.

**Comment by j2l** [comment]
Thank you @st8st8 
OK, I had an issue with email, I re-added ` 'oscar.apps.customer.auth_backends.EmailBackend',` in the AUTHENTICATION_BACKENDS to make it work, not sure why it was removed, and what the new `email/` folder is for.
Now I get a error regarding my stripe API version (I use the latest, 2023-10-16):
```
InvalidRequestError at /checkout/payment-details/

Request req_VtonVUh2QRLCin: You cannot use `line_items.amount`, `line_items.currency`, `line_items.name`, `line_items.description`, or `line_items.images` in this API version. Please use `line_items.price` or `line_items.price_data`. Please see https://stripe.com/docs/payments/checkout/migrating-prices for more information.
```
Indeed, it is at oscar_stripe_sca-sandbox/.venv/lib/python3.10/site-packages/oscar_stripe_sca/facade.py

**Comment by st8st8** [comment]
I'll add the EmailBackend back in, I was just trying to strip down to the minimum neccessary.

You are right, I need to update for more recent Stripe API versions, thanks for the reminder.

**Comment by st8st8** [comment]
I've added version 0.6 to github.  This allows anonymous checkout and updates for Stripe's Prices API (which is not used by default).  Two new settings have been added (STRIPE_COMPRESS_TO_ONE_LINE_ITEM and STRIPE_USE_PRICES_API) and one has been removed (STRIPE_CURRENCY)

**Comment by j2l** [comment]
Yes! Thank you @st8st8 
Now sandbox does work for me and I can start to learn from it :smile: .
Would you please update pypi from 0.3?

**Comment by j2l** [comment]
Hmm, sorry to bother again, but, even if the process works on the oscar side, Stripe doesn't  add the payment. Maybe the "place order" confirmation doesn't finalize on stripe side?

**Comment by st8st8** [comment]
OK - version 0.6.1 is available in PyPI....  I got another email about a  comment here about payments not coming through in Stripe - which I guess you've deleted? So I'll ignore that for now...

**Comment by j2l** [comment]
Thank you @st8st8 !
Yes, I deleted it ... after I realized my stripe keys were actually wrong but working! :rofl:

**Comment by st8st8** [comment]
Good stuff, and thanks for the continued feedback.  I might treat myself to closing this ticket after eight months then!
