### ISSUE TITLE
Payment does not include shipping

### ISSUE THREAD

**Issue by patrikniebur** [st8st8/django-oscar-stripe-sca#7]
Stripe payment includes all items correctly but does not consider shipping. I can't see shipping mentioned in source so I guess this is not a bug but not included in implementation. 

Can you please confirm if this was intentional omission? If not I can submit a PR

**Comment by st8st8** [comment]
Hey,

No - it's not intentional, we've just been using it for digital, so it's not implemented yet.  A PR would be welcome if you have one....

**Comment by st8st8** [comment]
Thanks for your help!
